### ISSUE TITLE
Find a way to pop up warning for users of ExFAT.

### ISSUE THREAD

**Issue by StevenMattera** [AtlasNX/Kosmos-Updater#15]
SDFiles Updater detected that your SD card is formatted as ExFAT. Please note that continue use of SDFiles Updater may cause corruption to your SD card. This is due to an issue with Nintendo's ExFAT driver, and is not a bug with SDFiles Updater. If you wish to continue you do so at your own risk and will not receive support from the SDFiles discord.

If you want to proceed anyways, press (A). Otherwise press (B) to exit.

**Comment by StevenMattera** [comment]
Also disable restart option.

**Comment by StevenMattera** [comment]
There is no (easy) way to detect an SD Card formatted as ExFAT. So next update will pop up a one time alert warning against corruption if our SD Card is formatted as ExFAT.

**Comment by fennectech** [comment]
Can we read arbitrary bytes from the sdcard? If we could get the FAT we could determine weather its exfat or not.
