### ISSUE TITLE
Ignore tag not working

### ISSUE THREAD

**Issue by fennectech** [AtlasNX/Kosmos-Updater#18]
I have ignore enabled like this but the files are still overwritten. 
`ignore = [ "sdmc:/switch/SDFilesUpdater/settings.cfg", "sdmc:/modules/sysftpd/sys-ftpd.kip", "sdmc:/atmosphere/loader.ini" ];`

**Comment by ThatNerdyPikachu** [comment]
Please don't open issues about this problem across multiple repos.

**Comment by fennectech** [comment]
I opened it across multiple repos/.  I thought it didn’t get saved when i went back to the repo so I redid it.   Link and ill close one.

**Comment by StevenMattera** [comment]
@ThatNerdyPikachu It's fine I would prefer people open issues on this repository if it's about SDFilesUpdater. @fennectech I realized I broke this when I switched from TAR to ZIP. I have this fixed in the repo now and should be going out with the next update soon.

**Comment by fennectech** [comment]
ive tried it on 3.0.0   same issue

**Comment by fennectech** [comment]
@StevenMattera   i still see the issue
