### ISSUE TITLE
2 cfw settings

### ISSUE THREAD

**Issue by Hapseleg** [AtlasNX/Kosmos-Updater#23]
Just a small thing which might cause some confusion for some ppl. I ran the updater and ended up with 2 "CFW Settings" now I got version 1.0.0 and 1.1.0, it seems the new one is the v1.0.0 since it has a logo in hbmenu I havent seen before.

Not sure why it happened but one of the toolkits is "CFWSettings.nro" and the other one is "CFW-Settings.nro", I just tried getting the latest from sdsetup and it is named "CFW-Settings.nro" just like on your github.

I deleted "CFWSettings.nro" which was the v1.1.0 (?) and now it ignores the settings I have setup in the CFW settings app, I guess another config file is overriding my settings? (I have HBMenu key combo set as left trigger but I have to use right trigger)

Keep up the great work guys <3

**Comment by StevenMattera** [comment]
Someone must have renamed it in the Kosmos repository. Not really much I can do. Newer versions of Kosmos Updater will delete the files it installed before when upgrading.

**Comment by fennectech** [comment]
im just glad it didnt erase my checkpoint directory xD
