### ISSUE TITLE
/atmosphere/titles got (partially?) skipped in 12.0.1 -> 12.1 process

### ISSUE THREAD

**Issue by Nolanlemahn** [AtlasNX/Kosmos-Updater#30]
```
I_Enjoy_Pastries_Far_Too_Much
I'm not seeing Emubiio in the Kosmos Toolbox. Am I missing something?

Nolan Wiki
(i had the same problem they had, but i was wondering where sys-clk was)
(turns out emuiibo AND ldn_mitm AND sys-clk weren't clobbered)

austin5623
i had that same issue but with hid-mitm
just wasn't there
```

Not sure why/how that's happening. (Don't "have the time" to compile/stress-test.) Seems like for whatever reason, the new titles weren't being added to `/atmosphere/titles`, so the KosmosToolbox (**correctly**) does not display them.

**Comment by StevenMattera** [comment]
Good catch. There was a few modules missing. If you reinstall with Kosmos Updater you will get the missing modules.
