### ISSUE TITLE
Master branch segfaults on latest dkA64

### ISSUE THREAD

**Issue by Swiftloke** [AtlasNX/Kosmos-Updater#32]
Not much to say. Download latest dkA64 and portlibs. (``pacman -Syu``) A build change/fail with latest stuff requires that you modify the Makefile such that LIBS is now as follows:
``` LIBS		:=	 `aarch64-none-elf-pkg-config SDL2_ttf SDL2_image SDL2_mixer SDL2_gfx --libs` \
				-lpng -lturbojpeg -lvorbisidec -logg -lmpg123 -lmodplug \
				-lconfig -lcurl -lz -lmbedtls -lmbedx509 -lmbedcrypto -lnx `sdl2-config --libs` `freetype-config --libs` ```
dkP team states that this change is unlikely to be the source of the crash.
make and run. Kosmos Updater begins to check for updates (after getting past the exFAT warning) then immediately dies. A crash dump can be found below.
[01561507295_010000000000100d.log](https://github.com/AtlasNX/Kosmos-Updater/files/3327653/01561507295_010000000000100d.log)

**Comment by StevenMattera** [comment]
I'm aware of this. I'm currently working on completely reworking Kosmos Updater in a private repo.

**Comment by StevenMattera** [comment]
This has now been fixed.
