### ISSUE TITLE
Opening always updates

### ISSUE THREAD

**Issue by zTKS** [AtlasNX/Kosmos-Updater#34]
After the 3.0.7 update, every time I open the updater it will always download the same update I already have installed and prompt to restart the application.

**Comment by StevenMattera** [comment]
I'm able to confirm this by installing 3.0.6. Not sure what is going on here. I've confirmed that 3.0.7 is being downloaded from the server so it must be something wrong in the app.

**Comment by zTKS** [comment]
I managed to fix it by swapping the nro file over with the latest one so I'm all fine now but not sure why that was happening.

**Comment by thunder-17** [comment]
It will update if there are not new versions of Kosmos to Install

**Comment by Poincare1** [comment]
maybe i'm missing something, but don't you put yourself/your switch at high risk of ban by being ONLINE with a CFW?!

**Comment by TheRealAman** [comment]
> maybe i'm missing something, but don't you put yourself/your switch at high risk of ban by being ONLINE with a CFW?!

yes, but there are ways to prevent connecting to nintendo servers while online
plus isn't this irrelevant to the issue?

**Comment by gr33k** [comment]
You can use Incognito to wipe your keys (make a backup hehe), or DNS solutions which block communications to Nint3ndo servers. I use Incognito on my EmuNAND and have WiFi connected for homebrew store and the like.

**Comment by tumGER** [comment]
I'd recommend using some DNS solution such as 90DNS or https://pegascape.sdsetup.com

**Comment by NicholeMattera** [comment]
Kosmos Updater 3.0.8 will fix this issue.
