### ISSUE TITLE
Hang on attempting to update Updater (3.0.8)

### ISSUE THREAD

**Issue by FelicitusNeko** [AtlasNX/Kosmos-Updater#36]
Updater 3.0.7 was hanging on attempting to update itself. I decided to manually check for an update, and saw that 3.0.8 acknowledged fixing a bug which prevented it from doing so. I updated manually, but the updater is still trying to update itself, and is still hanging when attempting to do so. The Homebrew Launcher clearly indicates that the Updater is on version 3.0.8. I have tried deleting the configuration and DB files and run a fresh installation, but the problem persists.

**Comment by NicholeMattera** [comment]
Needed to do a small fix on the server side. Try it now.

**Comment by FelicitusNeko** [comment]
Thanks, that works.
