### ISSUE TITLE
what even is this 

### ISSUE THREAD

**Issue by fennectech** [AtlasNX/Kosmos-Updater#37]
https://cdn.discordapp.com/attachments/478162551381819392/631663174927777792/wat.cfg   Kosmos updater has done this over the months and im not quite sure why.   but clearly    there might be an issue

**Comment by fennectech** [comment]
everything with two slashes is something i put    The rest is    uhh    Added by kosmosupdater

**Comment by NicholeMattera** [comment]
This started in v3.0.5. When you first updated after this version a dialog box popped up asking if you wanted to ignore config files. You must have choose yes, and thus it added the config files to your ignore list.

**Comment by fennectech** [comment]
there a crap ton of repeats of all the config files tho

**Comment by NicholeMattera** [comment]
I know some people were having config migration issues in the past. That should have been fixed in 3.0.8, so it shouldn't be happening anymore hopefully.
